"""add click count

Revision ID: 4b827e27596a
Revises: 5d97fb5b74cb
Create Date: 2026-07-18 19:51:09.553653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b827e27596a'
down_revision: Union[str, Sequence[str], None] = '5d97fb5b74cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "urls",
    sa.Column(
        "click_count",
        sa.Integer(),
        nullable=False,
        server_default="0",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'click_count')
    # ### end Alembic commands ###
